마이페이지 UI 제작
Parkjju/runnerpia pull request #21
Opened 2023-06-13 13:00 UTC by jessicakohh

<h2>작업 내용</h2>
<h2>1. MyPageViewController</h2>

![마이페이지](https://github.com/Parkjju/runnerpia/assets/108605997/c128f1a0-8714-405d-aae2-bb1dffce1308)

<ul>
<li><code>MyPageViewDelegate</code> 프로토콜을 채택하여 <code>MyPageView</code>에서 발생하는 이벤트를 처리합니다.</li>
</ul>
<h2>2. EmptyView</h2>

EmptyRecommendPageController | EmptyReviewController
-- | --
 ![Simulator Screenshot - iPhone 14 Pro - 2023-06-13 at 21 48 05](https://github.com/Parkjju/runnerpia/assets/108605997/8e23ce91-bba9-44f5-bcad-f840c1179062)  |  ![Simulator Screenshot - iPhone 14 Pro - 2023-06-13 at 21 48 38](https://github.com/Parkjju/runnerpia/assets/108605997/4591f772-bd07-4c08-a010-7fcb843f2298)

<ul>
<li><code>EmptyRecommendPageController</code>, <code>EmptyReviewController</code>  모두 <code>MyEmptyView</code>를 뷰로 설정하여 해당 뷰의 서브뷰 속성을 따로 설정하였습니다.</li>
<li><code>UINavigationBarAppearance</code>를 사용하여 NavigationBar 배경 색상 변경하였습니다.</li>
</ul>
<pre><code class="language-swift">let navigationBarAppearance = UINavigationBarAppearance()
navigationBarAppearance.backgroundColor = .white
navigationController?.navigationBar.standardAppearance = navigationBarAppearance
navigationController?.navigationBar.scrollEdgeAppearance = navigationBarAppearance
// 그림자 삭제
navigationBarAppearance.shadowColor = .clear
</code></pre>
<ul>
<li><code>NSAttributedString</code> 를 사용하여 <code>UIButton</code> 여백 관련 설정 변경하였습니다.</li>
</ul>
<pre><code class="language-swift">lazy var connectButton: UIButton = {
        let button = UIButton()
        button.backgroundColor = .blue400
        button.layer.cornerRadius = 25
        button.clipsToBounds = true
        button.setTitleColor(.white, for: .normal)
        var config = UIButton.Configuration.plain()
        config.titlePadding = 16
        button.configuration = config
        
        let attributedTitle = NSAttributedString(string: &quot;추천 경로 보러가기&quot;, attributes: [
            NSAttributedString.Key.font: UIFont.semiBold16,
            NSAttributedString.Key.foregroundColor: UIColor.white
        ])
        button.setAttributedTitle(attributedTitle, for: .normal)

        return button
    }()
</code></pre>
<ul>
<li>저희가 확장시켜놓은 <code>UIFont</code>를 확장시켜놓은 <code>.semiBold16</code> 설정이 적용되지 않아 사용하였는데, 버튼 내 text 양옆으로 여백을 주기 위해 <code>UIButton.Configuration</code>을 사용하는 경우 <code>titleLabel</code>의 폰트가 무시된다고 합니다. 기본 UIFont도 적용 안되기는 마찬가지더라고요..!</li>
</ul>
<h2>3. MyRunningView / MyReviewView</h2>

MyRunningView | MyReviewView
-- | --
![Simulator Screenshot - iPhone 14 Pro - 2023-06-13 at 21 49 15](https://github.com/Parkjju/runnerpia/assets/108605997/d60ddc09-042a-46a3-bda6-7547619d4485)  |  ![Simulator Screenshot - iPhone 14 Pro - 2023-06-13 at 21 49 42](https://github.com/Parkjju/runnerpia/assets/108605997/c94defd9-ce91-445d-9fce-d3b3d348cc62)

<ul>
<li><code>PhotoCollectionView</code>의 사진이 모두 채워지지 않았을때의 설정 추가하였습니다.</li>
<li><code>Route</code>모델을 기준으로 하드코딩된 데이터를 바인딩 시켜주는 방향으로 수정하였습니다.</li>
</ul>
<h2>4. 기타</h2>
<ul>
<li>TabBar 아이콘 및 메인 이미지 Figma 반영된대로 수정하였습니다.</li>
<li><code>UIFont</code> regular 속성 weight 부분 설정이 .semibold로 잘못되어있어서 .regular 로 수정하였습니다~</li>
</ul>
<h2>추후 수정사항</h2>
<ul>
<li><code>MyRunningView</code> 지도 로딩이 느린 문제</li>
<li><code>MyPageViewController</code> 설정 관련 페이지 추가</li>
<li><code>MyPageViewController</code> 빈 페이지와 데이터가 있는 페이지를 서버요청에 따라 분기 필요</li>
</ul>
<h2>질문</h2>
<ul>
<li><code>ViewController</code>에서 사용하는 뷰 인스턴스 저장속성에 등록하지않고 타입캐스팅하여 뷰에 반영하였는데, 맞게 한것인지 피드백 한번 부탁드립니다 ..! 🥹</li>
</ul>

2023-06-13 23:21 UTC, Parkjju requested changes
코멘트 몇가지 남겨드립니다 🚀 고생하셨어요!!

2023-06-13 23:21 UTC, Parkjju commented on runnerpia/Controllers/Main/My/MypageViewController.swift
> +    }
`emptyRecommendPageController`에도 백그라운드 `white`로 부여해주시는게 좋을 것 같아요!

https://github.com/Parkjju/runnerpia/assets/75518683/0b50118b-5144-4556-9bf3-d85470103d66

파일명도 `emptyRecommendPage~` 보다는 실제 기능을 가지고 있도록 하고 내부 로직 처리만 `empty`여부에 따라 다른 화면을 보이게 하면 좋을 것 같아요!

2023-06-13 23:21 UTC, Parkjju commented on runnerpia/Managers/MainViewManager.swift
>          items[2].title = "마이"
![스크린샷 2023-06-14 오전 8 04 45](https://github.com/Parkjju/runnerpia/assets/75518683/65ca11d6-c617-4d4d-8fbc-e221452e1ccf)

탭바 이미지가 제쪽에서는 안나타나는데 `withRenderingMode` 문제는 아닌 것 같고 `Assets.xcassets` 파일명이 아직 merge되지 않아서 nil이 반환되는 것 같아요!

제스님 환경에서 문제 없으시면 코멘트 남겨주세요! 병합하고 확인해보겠습니다 👍🏻

2023-06-13 23:21 UTC, Parkjju commented on runnerpia/Controllers/Main/My/EmptyView/EmptyRecommendPageController.swift
> +    }
이 부분 실제 `RouteRecord` 뷰컨이랑 화면 연결해주세요!

2023-06-13 23:21 UTC, Parkjju commented on runnerpia/Views/Main/My/Cell/MyReviewTableViewCell.swift
> +                cell.isChecked = true
`isChecked` 속성이 `true`로 설정되어 있으면 그래디언트는 적용되지 않습니다!

`TagCollectionViewCell` `setupUI` 함수 한번 살펴보시면 좋을 것 같아요!

2023-06-13 23:21 UTC, Parkjju commented on runnerpia/Controllers/Main/My/MyReviewViewController.swift
> +    }
경로 따라가기에서도 cell별로 UI를 구현한게 아니라 section별로 셀을 하나만 두어서 구현했었는데, 셀간 간격 부여를 위해서 하신거면 잘하신 것 같습니다 👍🏻👍🏻👍🏻👍🏻

2023-06-13 23:52 UTC, Parkjju requested changes

2023-06-13 23:52 UTC, Parkjju commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +        }
![스크린샷 2023-06-14 오전 8 37 03](https://github.com/Parkjju/runnerpia/assets/75518683/ed12330d-a3bf-4bcf-939b-a7543b7048a0)

셀 설정 관련 코드 문제는 아니었던 것 같고 오토레이아웃 설정이 잘못되어있네요.
`contentView.snp.bottom`이랑 `map.snp.top`을 뒤집어서 맞추신 이유가 따로 있으실까요??

2023-06-13 23:52 UTC, Parkjju commented on runnerpia/Controllers/Main/My/MyRunningViewController.swift
> +    }
여기는 테이블 뷰 셀간 간격 부여를 할 필요가 없는 UI라서 섹션으로 구현하지 않으셔도 좋을 것 같아요.
`numberOfRowsInSection`에 하드코딩 데이터 count값을 리턴해주시고 `cellForRowAt`에서도 `indexPath.row`로 바꿔주세요!

2023-06-13 23:52 UTC, Parkjju commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +        }
<img width="1041" alt="스크린샷 2023-06-14 오전 8 41 47" src="https://github.com/Parkjju/runnerpia/assets/75518683/3c26abca-fc16-436a-b20f-0422fbfed43d">

디자인과는 다르게 스택뷰 위아래가 살짝씩 어긋나고 있는 상태입니다!
map이 1차적으로 height값이 고정된 형태로 셀 안에 들어갈테니 스택뷰 top과 bottom을 맵이랑 맞춰주시고
그에 따른 스택뷰 내부 영역 설정도 추가로 수정해주셔야 할 것 같아요!

2023-06-13 23:52 UTC, Parkjju commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +            $0.leading.equalToSuperview().offset(Constraints.paddingLeftAndRight)
오토레이아웃을 맞추는 대상의 super뷰의 leading과 trailing이 화면 너비의 좌우측이 되는 것이 아니라 셀의 좌우측이 되어서 맵 뷰가 좀더 안쪽으로 들어오게 되는 것 같아요.

![스크린샷 2023-06-14 오전 8 47 22](https://github.com/Parkjju/runnerpia/assets/75518683/b236ed7c-635b-4b0f-a3d0-83f7a450f58e)

leading기준 offset 삭제해주세요

2023-06-13 23:52 UTC, Parkjju commented on runnerpia/Managers/MainViewManager.swift
>          setTapBarController()
`TabBarController` 이동하셔서 탭바 아이템 `didSelect` 프로토콜 메서드에서 마이페이지 뷰 컨트롤러 메모리에서 해제시켜주도록 로직 추가가 필요할지 고민해보시고 말씀해주세요!

2023-06-14 12:46 UTC, jessicakohh commented on runnerpia/Managers/MainViewManager.swift
>          items[2].title = "마이"
제 환경에서는 문제없이 나옵니다!

2023-06-14 12:46 UTC, jessicakohh commented on runnerpia/Controllers/Main/My/MyReviewViewController.swift
> +    }
변경하였습니다!

2023-06-14 12:46 UTC, jessicakohh commented on runnerpia/Views/Main/My/Cell/MyReviewTableViewCell.swift
> +                cell.isChecked = true
변경하였습니다!

2023-06-14 12:46 UTC, jessicakohh commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +        }
변경하였습니다!

2023-06-14 12:48 UTC, jessicakohh commented on runnerpia/Controllers/Main/My/MyRunningViewController.swift
> +    }
변경하였습니다!

2023-06-14 12:49 UTC, jessicakohh commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +        }
변경하였습니다!

2023-06-14 12:50 UTC, jessicakohh commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +            $0.leading.equalToSuperview().offset(Constraints.paddingLeftAndRight)
leading기준 offset 삭제하면 첨부해주신 파일처럼 나오고, offset을 적용하면
![Simulator Screenshot - iPhone 14 Pro - 2023-06-14 at 21 45 30](https://github.com/Parkjju/runnerpia/assets/108605997/fe21cd89-68c5-4341-ae9e-6d348514efdf)
leading에 맞게 나오는 것 같은데 확인 부탁드립니다..!

2023-06-14 20:40 UTC, Parkjju commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +            $0.leading.equalToSuperview().offset(Constraints.paddingLeftAndRight)
leading을 `총 n`개 UILabel에 맞추도록 디자인 되어 있어서 offset은 삭제해주시는게 좋을 것 같아요!!

<img width="627" alt="스크린샷 2023-06-15 오전 5 39 04" src="https://github.com/Parkjju/runnerpia/assets/75518683/5fa9984e-6b14-44c5-8f34-1fb6fbad6102">

2023-06-14 22:53 UTC, jessicakohh commented on runnerpia/Views/Main/My/Cell/MyRunningViewTableViewCell.swift
> +            $0.leading.equalToSuperview().offset(Constraints.paddingLeftAndRight)
넵! 확인감사합니다!

2023-06-15 05:27 UTC, jessicakohh commented on runnerpia/Controllers/Main/My/EmptyView/EmptyRecommendPageController.swift
> +    }
완료했습니다!

2023-06-18 05:48 UTC, jessicakohh commented on runnerpia/Managers/MainViewManager.swift
>          setTapBarController()
마이페이지 뷰 컨트롤러 메모리에서 해제하는 로직 추가하였습니다!

2023-06-18 05:50 UTC, jessicakohh commented
**MyReviewViewController**

- background에 색상을 둔 후 테이블 뷰 간격 부여해서 나눈 후 Figma구현대로 하는 것이 뷰의 전체 색상까지 반영되어서 어렵더라고요.. 우선 tableView 내부에서 만들어놓긴 했는데 저번에 말씀해주신것처럼 패딩값 없이 구현하는 방법이 있을까요..!

**MyRunningViewController**

- EmptyView가 필요한 화면에서는 각각 Controller를 두는 대신에 데이터 여부에 따라서 EmptyView가 보여지는것으로 변경했는데요, 현재 뷰로 설정해놓은 myRunningView가 아닌 EmptyView를 타입캐스팅하면 오류가 나서 
`weak var emptyRecommendView: MyEmptyView?` 약한참조로 선언하였는데.. 피드백 부탁드립니다..!

2023-06-21 01:51 UTC, Parkjju requested changes

2023-06-21 01:51 UTC, Parkjju commented on runnerpia/Views/Main/My/MyRunningView.swift
> +    }
이쪽에서 테이블뷰 leading에 16포인트 부여해두면 

![스크린샷 2023-06-21 오전 10 49 16](https://github.com/Parkjju/runnerpia/assets/75518683/d0671813-80c0-4a99-9f1b-ca4f3236d235)

위와 같이 테이블뷰와 셀들 총 개수를 나타내는 UILabel이 어긋나게 되는데요! 테이블뷰 자체 leading offset을 지우게 되면

![스크린샷 2023-06-21 오전 10 50 06](https://github.com/Parkjju/runnerpia/assets/75518683/71831651-9675-439e-ab6f-f02532447e28)

이런식으로 일직선 배치가 되어서 디자인이랑 동일하게 나타나는 것 같아요! 위와 같이 수정해주시면 감사하겠습니다~!

2023-06-21 01:51 UTC, Parkjju commented on runnerpia/Views/Main/My/MyReviewView.swift
> +        }
여기도 마찬가지로 leading offset 삭제해주세요!

2023-06-21 01:53 UTC, Parkjju commented
> **MyReviewViewController**
> 
> * background에 색상을 둔 후 테이블 뷰 간격 부여해서 나눈 후 Figma구현대로 하는 것이 뷰의 전체 색상까지 반영되어서 어렵더라고요.. 우선 tableView 내부에서 만들어놓긴 했는데 저번에 말씀해주신것처럼 패딩값 없이 구현하는 방법이 있을까요..!
> 
> **MyRunningViewController**
> 
> * EmptyView가 필요한 화면에서는 각각 Controller를 두는 대신에 데이터 여부에 따라서 EmptyView가 보여지는것으로 변경했는데요, 현재 뷰로 설정해놓은 myRunningView가 아닌 EmptyView를 타입캐스팅하면 오류가 나서
>   `weak var emptyRecommendView: MyEmptyView?` 약한참조로 선언하였는데.. 피드백 부탁드립니다..!

padding 부여된 디바이더도 나름대로 괜찮은 것 같은데 이건 추후 지연님과 미팅할때 논의해보면 좋을 것 같습니다!

2023-06-21 02:13 UTC, Parkjju requested changes

2023-06-21 02:13 UTC, Parkjju commented on runnerpia/Controllers/Main/My/MyRunningViewController.swift
> +        let emptyView = MyEmptyView()
route 저장속성에 데이터들이 바인딩 된 이후라면 MyEmptyView 인스턴스를 생성하지 않아도 되지 않을까요??

현재는 viewDidLoad함수 내에서 route데이터가 존재하는지 여부에 상관없이 `configureEmptyView()`라는 함수가 무조건적으로 실행되고 있는데, 그게 아니라 route 데이터 여부에 따라 configureEmptyView 메서드를 호출할지 여부를 한번 분기처리 하면 좋을 것 같아요!

추가) 만약 routeData에 따라 더 이상 emptyRecommendView가 사용되지 않는다면 removeFromSuperview와 같은 메서드 호출을 통해 뷰컨트롤러로에 적재되어 있는 UIView 인스턴스를 삭제해주는게 좋을 것 같습니다!

2023-06-21 11:13 UTC, Parkjju approved these changes

2023-06-21 11:13 UTC, merged